export const GET_EMPLOYMENTS = "GET_EMPLOYMENTS";
export const ADD_EMPLOYMENT = "ADD_EMPLOYMENT";
export const DELETE_EMPLOYMENT = "DELETE_EMPLOYMENT";
export const UPDATE_EMPLOYMENT = "UPDATE_EMPLOYMENT";
